### ISSUE TITLE
libg4sipm_sample.so: undefined reference

### ISSUE THREAD

**Issue by Lupesaez** [ntim/g4sipm#3]
Hello, 

I am trying to install the g4SiPM module in an Ubuntu 16.04.1 with a geant4 version geant4-10.2.3. When I try to compile, I get this error :

[ 98%] Linking CXX executable sample
libg4sipm_sample.so: undefined reference to `TString::TString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
sample/CMakeFiles/sample.dir/build.make:150: recipe for target 'sample/sample' failed
make[2]: *** [sample/sample] Error 1
CMakeFiles/Makefile2:1048: recipe for target 'sample/CMakeFiles/sample.dir/all' failed
make[1]: *** [sample/CMakeFiles/sample.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

¿Do you have any clue about what is wrong?

thanks in advance

**Comment by ntim** [comment]
Hi, the error says that the linking process (it is 'ld') can not find the implementation to the interface of TString::TString(std::string, ...). Since this should be supplied by a ROOT library, please check if all the libraries are included in the linking process by running the cmake configuration.
